pypi-certbot: Autospec creation for update from version 2.2.0 to version 2.3.0
Alex Zorin (4):
      account: stop storing legacy new_authzr_uri
      fix lint
      remove docstring for removed argument
      remove unused attributes from test

Alexis (1):
      Create SECURITY.md (#9566)

Brad Warren (20):
      Add contents to certbot/CHANGELOG.md for next version
      Bump version to 2.3.0
      disable random sleep in lock_test.py (#9545)
      Fix tox environments (#9547)
      Start sending coverage data to codecov (#9544)
      double progressive percentage (#9557)
      Change coverage upload condition (#9552)
      fix requests-toolbelt warning (#9569)
      reset set_by_cli between each test (#9567)
      Remove code testing testing code
      Remove most progressive release tooling
      remove 1.32.x deps
      always push to beta
      update snapcraft credentials
      fail faster if we try to use candidate
      tweak cloudxns condition
      Update and run isort (#9573)
      Automatically run test files with pytest (#9576)
      disable stale for PRs
      tweak comment

Daniel McMahon (1):
      Fix docs google permissions (#9556)

Will Greenberg (5):
      acme.messages.Error: add mutability (#9546)
      Replace probot/stale app with a Github Action (#9466)
      Bump up the number of operations to 30 (#9554)
      Update changelog for 2.3.0 release
      Release 2.3.0

alexzorin (9):
      docs: give webroot and standalone better descriptions (#9536)
      Deprecate {csr, keys} dirs & automatically truncate lineages (#9537)
      certbot-ci: boulder only supports port 80 for http-01 (#9548)
      show_account: display account thumbprint (#9540)
      docs: update -d flag copy to be CA-agnostic (#9542)
      docs: generate a man page with a structure (#9561)
      repin cryptography for openssl security update (#9565)
      docs: document reconfigure verb (#9563)
      certbot-ci: fix crash in and simplify manual_http_hooks (#9570)

ohemorange (2):
      Configuration File Update w/o Certificate Issuance (#9355)
      Fix typo direcory --> directory in --run-deploy-hooks help (#9568)